export * from "./home/home"
export * from "./login/login"
export * from "./hospital-list/hospital-list"
export * from "./patient-type/patient-type"
export * from "./patient-registration/patient-registration"
export * from "./visit-time/visit-time"
export * from "./polyclinic-list/polyclinic-list"
export * from "./queue-no/queue-no"
